name: fittrack_pro
description: "Fitness tracking app with advanced UI and native integrations"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  flutter_local_notifications: ^19.3.0
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/
